name: Build and Deploy Components+Style Guide
on:
  push:
    paths: ["web/stories/**", "web/components/**"] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: webv2 # Remove when webv2 gets merged into develop

      - name: Install and Build
        run: | # Install npm packages and build the Storybook files
          cd web
          npm install --include-dev
          npm run build-storybook -- -o ../docs/components

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Owncast
          author_email: owncast@owncast.online
          message: "Commit updated components/styles"
          add: "docs/components"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dispatch event to owncast/owncast
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ADMIN_BUNDLE_PAT }}
          repository: owncast/owncast.github.io
          event-type: bundle-components-library
