name: Bundle and bundle web app into Owncast codebase
on:
  push:
    paths:
      - web/**

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Bundle web app (next.js build)
        uses: actions/checkout@v3
      - run: build/web/bundleWeb.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Bundle embedded web app'
          add: 'static/web'
